### ISSUE TITLE
Null [Pointer] Exception Checker (NEC)

### ISSUE THREAD

**Issue by drex44** [open-source-ideas/open-source-ideas#109]
## Project description

A library like lodash.js or Numpy which applies the basic checks such as the null check, NaN check, empty string, only space in string etc.

It will be called Nec (Null Exception Checker).
I would be happy to contribute if someone is there to contribute and validate the idea.

## Relevant Technology

This library can be created on most of the platforms so everybody despite the language, can use this library.
People familiar with below technology would be helpful,
- Javascript
- Python

For starters,
- Nec.js library for performing various checks in javascript.
- Nec.py in python.

## Complexity and required time

[_Please only tick off one box in each category by changing `[ ]` to `[x]`. The labels on the project will then be updated by the maintainers as soon as possible._]

### Complexity

- [ ] Beginner - This project requires no or little prior knowledge of the technolog(y|ies) specified to contribute to the project
- [x] Intermediate - The user should have some prior knowledge of the technolog(y|ies) to the point where they know how to use it, but not necessarily all the nooks and crannies of the technology
- [ ] Advanced - The project requires the user to have a good understanding of all components of the project to contribute

### Required time (ETA)

- [ ] Little work - A couple of days
- [x] Medium work - A week or two
- [ ] Much work - The project will take more than a couple of weeks and serious planning is required

**Comment by GCHQ77703** [comment]
Most of these checks might be easier to write using the standard library, in JavaScript at least, as opposed to in a module.  Some examples:

```javascript
// check if a variable is null
variable === null

// check is a variable is not a number
isNaN(variable)

// check if the variable is an empty string
variable === ''

// check if a variable is a single space
variable === ' '
```

You may have success creating a helper function for 'empty' seeming values by chaining these together:

```javascript
function isEmpty(variable) {
  return typeof variable === 'undefined' || variable === null || isNaN(variable) || variable === '' || variable === ' '
}
```

You may also be able to handle a large number of cases due to JavaScript's creative handling of type coercion to booleans.  Whereupon a number of empty types will return false if you just do `!variable`.  This will match things like `false`, `0`, `''`, `null`, `undefined`, etc.

**Comment by Solero93** [comment]
I agree with @GCHQ77703 because both Python and JavaScript consider these values _falsy_ as in they evaluate to false when used as a boolean expression. 

See [Python reference](https://docs.python.org/3.7/library/stdtypes.html#truth-value-testing) for _falsy_ values in Python

See [JavaScript reference](https://developer.mozilla.org/en-US/docs/Glossary/Falsy) for _falsy_ values in JavaScript

Adding an extra dependency to any project for such simple check would be a very bad idea in my opinion. Also, in a normal language "empty" is a very broad term, so it should be implemented according to your domain.
However, if the _falsy_ values are too broad for your usage, either define a function like @GCHQ77703 did or you can write something like:

```python
# Check if variable is empty, but not empty list nor empty string
def isEmpty(variable):
    return not variable and variable not in ('', [])

>>> isEmpty('')
False
>>> isEmpty(False)
True
>>> isEmpty(None)
True
>>> isEmpty([])
False
>>> isEmpty(())
True
```

**Comment by drex44** [comment]
correct, I think this may be one project-specific need and creating a wrapper function is a good idea. With this, I will close this idea. thank you for the feedback! @GCHQ77703  and @Solero93.
