### ISSUE TITLE
FiraFlott

### ISSUE THREAD

**Issue by Sync-Codes** [open-source-ideas/open-source-ideas#116]
## Project description
Agreed that lately Operator Mono and Italic Ligatures have become a popular topic among developers nowadays. But this combination is not for free and many developers does not want to pay several dollars for just a font.

## Relevant Technology
I was using Fira Code for a while which worked pretty fine for me....but not for a long time.
I came across [FiraFlott](https://github.com/kosimst/FiraFlott). It was a mashed up combination of  Fira Code and FlottFlott with amazing Italic ligatures, made possible by @kosimst . Screenshots below.

## Screenshot
![FiraFlott](https://user-images.githubusercontent.com/37131433/46219901-33ec3a00-c366-11e8-9c14-03a561fa8dfa.PNG)

**Comment by KOLANICH** [comment]
And,  what is the idea?

**Comment by Sythe2954** [comment]
This was the idea itself. To use FiraFlott.

**Comment by StefansArya** [comment]
I have used FiraFlott when the second meeting with VSC.
This interface modification is optional for developers.
And developers are more often looking for plugins that can help their work.

But because VSC was taking a lot of memory, I'm returning to Sublime Text.

![code_2018-10-13_12-02-05](https://user-images.githubusercontent.com/11073373/46901752-3a8cbc80-cee3-11e8-9673-1f763f8f8321.png)

**Comment by FredrikAugust** [comment]
Don't want to be stackoverflow, but I think this is a bit off-topic. Rather post it in the discussion about alternatives to the what's-its-name font :)
