### ISSUE TITLE
Build something awesome: A platform for developers to meet, build, and ship software together.

### ISSUE THREAD

**Issue by roymoran** [open-source-ideas/open-source-ideas#195]
### Update: 
We've started working on this project on [slack](https://join.slack.com/t/project-unic0rn/shared_invite/enQtNzIwMjQ0NDMzODQ2LTdlNDA1MDViMTMzOGYzYzJjM2Q4N2ZmMjQyYWQxNjBiMjkxOTk4MGE0MmZmZTZkMTM1ZTliMmYyYjU3ZjdjMTM). I'm on there as roy - DM me if you'd like to contribute.

## Project description

This idea is partially inspired by this initiative, I would like to build a web app that lets developers meet build and ship software projects together for fun or profit. This project will have a frontend hooked up to a rest api that persists data to some storage. 

The backend will be a set of rest endpoints that will serve up data to the UI. The UI will allow developers to filter/sort projects based on their experience, technical abilities, or interests. Down the line it would be cool to have a recommendation engine that helps developers get matched to projects based on their elected experience/skillset.

[https://projectunicorn.net](https://projectunicorn.net) is the current site. It's written with Gatsby so mainly static. But the next step would be to make it a full fledged web app.

## Relevant Technology

- Frontend: Gatsby, React, TypeScript. 
- Backend: .NET Core, EF Core, MySQL, Slack/Discord API

### Complexity

- [ ] Beginner - This project requires no or little prior knowledge of the technolog(y|ies) specified to contribute to the project
- [x] Intermediate - The user should have some prior knowledge of the technolog(y|ies) to the point where they know how to use it, but not necessarily all the nooks and crannies of the technology
- [ ] Advanced - The project requires the user to have a good understanding of all components of the project to contribute

### Required time (ETA)

- [ ] Little work - A couple of days
- [ ] Medium work - A week or two
- [x] Much work - The project will take more than a couple of weeks and serious planning is required

### Categories

- [ ] Mobile app
- [ ] IoT
- [x] Web app
- [x] Frontend/UI
- [ ] AI/ML
- [ ] APIs/Backend
- [ ] Voice Assistant
- [ ] Developer Tooling
- [ ] Extension/Plugin/Add-On
- [x] Design/UX
- [ ] AR/VR
- [ ] Bots
- [ ] Security
- [ ] Blockchain
- [ ] Futuristic Tech/Something Unique

**Comment by roymoran** [comment]
Feedback or additional ideas are welcomed!

**Comment by rickywid** [comment]
Looks like a good starting point. There are some areas we need to discuss with the rest of team such as:
**How are we going to retain members and keep them engaged**
This topic has been an issue we've been trying to tackle since the early stages of PU. We already tried some methods such as weekly-progress reports, team-lead calls, PU admins providing support to other team-leads etc....

**There should be some sort of criteria before launching a PU project to the public**
We want to make sure PU is known for shipping projects to the highest standard. I think this is vital to PU's success. If we gain the reputation of launching bug ridden applications then it's definitely going to detract new users from joining and even cause existing members to leave.

I think PU has the potential to grow into a large community where developers can come together, collaborate, have fun and build cool shit.

**Comment by mittalyashu** [comment]
I really love the idea, but most of the time when people start to create this kind of project they just end up in creating a slack community.

### Suggestions

* Connect with GitHub/GitLab/BitBucket for login since it's all about developers
* Use GitHub/GitLab/BitBucket APIs to fetch open source project _(title, description, tags, languages)_ and show them on website based on used interests.

**Comment by roymoran** [comment]
Your suggestions make a lot of sense. In this case we should be able to integrate some of these apis like GitHub and Slack.

**Comment by mittalyashu** [comment]
What do you think about the tech stack?

My go to tools would be: Node.js, Vue.js, PostgreSQL/MongoDB, ExpressJS.

**Comment by roymoran** [comment]
@mittalyashu We've started the planning, design, and some of the development. Most of us are devs - so happy to get a hand on design and dev work too. here's what we're thinking for the tech stack. 

- Frontend: Gatsby, React, TypeScript. 
- Backend: C#/.NET Core, EF Core, MySQL, Slack/Discord API

**Comment by roymoran** [comment]
We're working on this on slack. If interested join [here](https://join.slack.com/t/project-unic0rn/shared_invite/enQtNzIwMjQ0NDMzODQ2LTdlNDA1MDViMTMzOGYzYzJjM2Q4N2ZmMjQyYWQxNjBiMjkxOTk4MGE0MmZmZTZkMTM1ZTliMmYyYjU3ZjdjMTM) and DM me. I'm on there as @roy.

**Comment by FredrikAugust** [comment]
This has been completed!

Check out the product over at [projectunicorn.net](https://projectunicorn.net/), and the source code at [projectunic0rn/pub](https://github.com/projectunic0rn/pub).

Amazing work everyone who contributed to the project! I can't wait to see the product evolve and grow :)
