### ISSUE TITLE
MySQL/Postgres ER diagram generator

### ISSUE THREAD

**Issue by Thrilleratplay** [open-source-ideas/open-source-ideas#22]
## Project description

Autogenerate , or load cached, force layout node graph, [example](http://vowl.visualdataweb.org/webvowl), by reading the information_schema metadata from MySQL/Postgres/Oracle/SQL Server.  Node tethers would represent foreign keys. Hovering or highlighting a node could show the table description. 

Security should be the first priority, followed by performance and usability.
## Relevant Technology

The example is [Ontology Visualization from d3.js Gallery](https://github.com/d3/d3/wiki/Gallery).  
## Who is this for

Advanced experience.

**Comment by Nzen** [comment]
Perhaps consider [schemaspy](https://github.com/schemaspy/schemaspy). The graphs are columnar, rather than force directed. I sense an implied desire that this be a webservice. SchemaSpy makes a static website of the tables with diagrams. If one were to put that behind a normal webserver, that could satisfy the idea presented here.

**Comment by Thrilleratplay** [comment]
[SchemaSpy](https://github.com/schemaspy/schemaspy) is the essence of the idea I had.  @Nzen 
 Thank you.
