### ISSUE TITLE
Justice online for LATAM

### ISSUE THREAD

**Issue by sanchezcarlosjr** [open-source-ideas/open-source-ideas#238]
## Project description
https://www.youtube.com/watch?v=XlqmCLr97dU

## Relevant Technology
An open-source platform for justice online as ERP justice. Maybe this is a startup idea. Maybe an ISO justice standard.  

### Complexity

- [ ] Beginner - This project requires no or little prior knowledge of the technolog(y|ies) specified to contribute to the project
- [ ] Intermediate - The user should have some prior knowledge of the technolog(y|ies) to the point where they know how to use it, but not necessarily all the nooks and crannies of the technology
- [x] Advanced - The project requires the user to have a good understanding of all components of the project to contribute

### Required time (ETA)

- [ ] Little work - A couple of days
- [ ] Medium work - A week or two
- [x] Much work - The project will take more than a couple of weeks and serious planning is required

### Categories

- [x] Mobile app
- [ ] IoT
- [ ] Web app
- [ ] Frontend/UI
- [ ] AI/ML
- [ ] APIs/Backend
- [ ] Voice Assistant
- [ ] Developer Tooling
- [ ] Extension/Plugin/Add-On
- [ ] Design/UX
- [ ] AR/VR
- [x] Bots
- [ ] Security
- [x] Blockchain
- [ ] Futuristic Tech/Something Unique

**Comment by KOLANICH** [comment]
Please, either put the text describing your idea instead of youtube (Google proprietary piece of shit) link, or close the issue.

And, please, say more clearly. I don't understand what you mean.

Also: "third world" is the term of Cold war times meaning states that have claimed neutrality. After the dissolution of Sovet Union and losing its status as a superpower the term has lost its meaning.
