### ISSUE TITLE
Migrate from GitHub

### ISSUE THREAD

**Issue by KOLANICH** [open-source-ideas/open-source-ideas#67]
Consider moving away from GitHub due to the recent (though still open) acquisition by Microsoft and taking into account what Microsoft have made to its own websites (they (at least some of them) don't work at all without JavaScript enabled and have tracking scripts, if M$ done this (or something else unfriendly, like unfriendly shifts in privacy policy) to GitHub, I (and I guess some other self-respecting people) will have to delete my account). Also GH is a de-facto proprietary monopoly, and having monopolies is bad, so I have thought long ago about migrating to GL (which is free software, even though the company running it seems to be unfriendly (the service Gitter owned by that company uses browser fingerprinting), the fact the software is free allows people to fork the software and migrate to own (or third-party) servers), but there are too little devs using it. But now, when the exodus from GH has started, it's a good opportunity to join the movement and make the market a little bit less monopolised.

**Comment by EMCM** [comment]
Why? What's the reason for doing so?

**Comment by FredrikAugust** [comment]
Presumably because of the recent acquisition by Microsoft.

Although I would like to migrate away from github, I think that would kill this community rather efficiently, as github is still the dominating platform for OSS.

**Comment by georoot** [comment]
https://github.com/open-source-ideas/open-source-ideas/issues/29#issuecomment-394415726 this might be something of a related issue, which i worked on some time ago. Afraid it's not at par with github and currently as far as i remember only allow some very basic functionality.

**Comment by FredrikAugust** [comment]
Why not move to GitLab? Which is fully functional, and ships with a lot of the features GitHub has?

**Comment by FredrikAugust** [comment]
Though @KOLANICH, please provide at least an explanation as to why we should do/consider this. This issue isn't really contributing to anything.

**Comment by KOLANICH** [comment]
@FredrikAugust I have updated the top comment.

**Comment by FredrikAugust** [comment]
Wonderful, thanks. 


Отправлено со смартфона Samsung Galaxy.
-------- Исходное сообщение --------От: KOLANICH <notifications@github.com> Дата: 20.06.18  9:08 ПП  (GMT+01:00) Кому: open-source-ideas/open-source-ideas <open-source-ideas@noreply.github.com> Копия: "Fredrik A. Madsen-Malmo" <mail.fredrikaugust@gmail.com>, Mention <mention@noreply.github.com> Тема: Re: [open-source-ideas/open-source-ideas] Migrate from GitHub (#67) 
@FredrikAugust I have updated the top comment.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.
{"@context":"http://schema.org","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"https://github.com/open-source-ideas/open-source-ideas/issues/67#issuecomment-398863009","url":"https://github.com/open-source-ideas/open-source-ideas/issues/67#issuecomment-398863009","name":"View Issue"},"description":"View this Issue on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"https://github.com"}}
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/open-source-ideas/open-source-ideas","title":"open-source-ideas/open-source-ideas","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/open-source-ideas/open-source-ideas"}},"updates":{"snippets":[{"icon":"PERSON","message":"@KOLANICH in #67: @FredrikAugust I have updated the top comment."}],"action":{"name":"View Issue","url":"https://github.com/open-source-ideas/open-source-ideas/issues/67#issuecomment-398863009"}}}
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [open-source-ideas/open-source-ideas] Migrate from GitHub (#67)",
"sections": [
{
"text": "",
"activityTitle": "**KOLANICH**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@KOLANICH",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"open-source-ideas/open-source-ideas\",\n\"issueId\": 67,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"open-source-ideas/open-source-ideas\",\n\"issueId\": 67\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/open-source-ideas/open-source-ideas/issues/67#issuecomment-398863009"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 342167713\n}"
}
],
"themeColor": "26292E"
}

**Comment by KOLANICH** [comment]
<details>
<summary>offtop</summary>
@FredrikAugust 
1 Вот вы и спалились ...
2 А что json делает в почтовом сообщении от гитхаба?
</details>

**Comment by FredrikAugust** [comment]
Я не знаю, лол

**Comment by mikaelbr** [comment]
I don't think we should take any rash decisions, and make a big deal out of currently nothing. These are all hypothetical worries motivated by, in my mind, something other than what is best for the initiative. It seems more motivated by the archaic notion that everything MS is evil by default. Even transitive ownership. This also evident by referring to Microsoft as `M$`.

I would also please ask, @KOLANICH, to refrain from wording like `[...] self-respecting people will have to delete my account [...]`, which is implying some sort of moral high grown towards other people not sharing your view.

**Comment by FredrikAugust** [comment]
Though I agree with a lot of your points @mikaelbr, the worries brought on by the acquisition are not hypothetical, they are real, and justifiable just by looking at the list of [217 companies MS have acquired](https://en.wikipedia.org/wiki/List_of_mergers_and_acquisitions_by_Microsoft). It is hard not to look at that with skepticism. Whether Microsoft eventually proves said worries to be rational, or if things remain the way they are today - only time will tell. But not preparing for the possible negative outcome would be silly, and I definitively think it is something worth discussing.

I for one will probably not stand behind this initiative are Microsoft to start interfering with the platform, or as mentioned, the privacy policy.

Continuing, you say these proposed changes are not motivated by the motive of the initiative, with which I agree, but it does say a lot about the organizations values, and we should keep that in mind as new users arrive.

And finally, if we want this initiative to continue growing, we need to start looking for alternative ways of attracting users. As of now, 25 of the 60 open issues are created by @KOLANICH, and a very large portion of the activity over the last months has been him/her creating new issues, and me labeling them. If you (@mikaelbr) need any help with that; send me an email, and I'll see what I can contribute with. 

_ps_: I am not representative of the initiative as a whole, so bear in mind these are my opinions, and you should make up your own.

**Comment by mikaelbr** [comment]
Moved to https://github.com/open-source-ideas/meta/issues/4
