### ISSUE TITLE
Add programming language tags

### ISSUE THREAD

**Issue by dannycolin** [open-source-ideas/open-source-ideas#76]
## Proposed change

Add programming language tags to issues and also show them on the website

## Motivation

This would help people to filter project ideas by programming languages.

## Proposed implementation

- Create a set of tags with the same color that looks like `language : JavaScript`
- Show them on the website. (btw where's the website source code, if we want to help?)

Suggestions, ideas are welcomed.

**Comment by FredrikAugust** [comment]
Hello,
Great suggestion, though there are quite some cases where the idea doesn't specify a programming language. Should we just ignore the tag on those? Or perhaps have a `language: any`? 
The source code can be found at my profile, under open-source-ideas-website (IIRC). At one point I will transfer it to this org, and make GitHub pages pull from that or a submodule here, instead of the current solution which I believe is to copy the repo content into `.ghpages`, or the gh-pages branch (don't remember which approach we went for). 


Sent from my Samsung Galaxy smartphone.
null

**Comment by FredrikAugust** [comment]
Would be great to get an opinion from @mikaelbr before implementing something like this.

**Comment by FredrikAugust** [comment]
There we go @dannycolin. Tranferred the ownership to this organization and added a link in the README. The code hasn't been touched in ages (and to be fair, could do with a rework), so if you wanna remake/improve it, go ahead! 

If you have any questions, would like help, or anything, don't hesitate to contact me! :smile:

**Comment by dannycolin** [comment]
I think `language : any` should be enough but if anyone have a better solution i'm all ears ;). @FredrikAugust btw for the website, IIRC you can name the repository like so : `open-source-ideas.github.io` and it'll be automatically use by GitHub to create a website to the same URL address.

**Comment by FredrikAugust** [comment]
Yeah, github pages for a user/org. That's probably better now that we've migrated. I'll do it right now :) Thanks for the tip @dannycolin. 

And I agree that `language: any` should be enough, but if the task allows for it, I'd rather have `language: low-level` for tasks that require it (e.g. embedded etc.) and `language: high-level` for programming tasks where such fine grain control is not needed.

**Comment by FredrikAugust** [comment]
Ta-da! Removed the `docs/` dir from this repo (and updated `README` links) and moved it over to open-source-ideas/open-source-ideas.github.io. Now that's all set and done for people to contribute! If you have any ideas for improvement, please don't hesitate to submit an issue on that repo, and I'll take a look (or better yet, submit a PR)! deddcc43b47dfa54ad6c69d7405d80b224784730 and 8c55822e5f4f35ddfcbdecc7a7d43fd5672637e4.

**Comment by KOLANICH** [comment]
The problem with `any` and `low-levep` tags is that they don't make search easier. For example a c++ dev comes. He searches for c++ and doesn't find some projects because they have no C++ tag. The same problem with missing tags. The one reporting the idea may not know that some language which suits better: the one chosen by the idea implementer. So it may be better to have no PL tags at all.

**Comment by FredrikAugust** [comment]
That's a fair point. I think I'll just let this one stay open in case anyone comes along with a solution that also considers that point. 


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: KOLANICH <notifications@github.com> Date: 05/08/2018  8:59 pm  (GMT+01:00) To: open-source-ideas/open-source-ideas <open-source-ideas@noreply.github.com> Cc: Fredrik August Madsen-Malmo <mail.fredrikaugust@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [open-source-ideas/open-source-ideas] Add programming language tags (#76) 
The problem with any and low-levep tags is that they don't make search easier. For example a c++ dev comes. He searches for c++ and doesn't find some projects because they have no C++ tag. The same problem with missing tags. The one reporting the idea may not know that some language which suits better: the one chosen by the idea implementer. So it may be better to have no PL tags at all.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/open-source-ideas/open-source-ideas","title":"open-source-ideas/open-source-ideas","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/open-source-ideas/open-source-ideas"}},"updates":{"snippets":[{"icon":"PERSON","message":"@KOLANICH in #76: The problem with `any` and `low-levep` tags is that they don't make search easier. For example a c++ dev comes. He searches for c++ and doesn't find some projects because they have no C++ tag. The same problem with missing tags. The one reporting the idea may not know that some language which suits better: the one chosen by the idea implementer. So it may be better to have no PL tags at all."}],"action":{"name":"View Issue","url":"https://github.com/open-source-ideas/open-source-ideas/issues/76#issuecomment-410540340"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/open-source-ideas/open-source-ideas/issues/76#issuecomment-410540340",
"url": "https://github.com/open-source-ideas/open-source-ideas/issues/76#issuecomment-410540340",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [open-source-ideas/open-source-ideas] Add programming language tags (#76)",
"sections": [
{
"text": "",
"activityTitle": "**KOLANICH**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@KOLANICH",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"open-source-ideas/open-source-ideas\",\n\"issueId\": 76,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"open-source-ideas/open-source-ideas\",\n\"issueId\": 76\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/open-source-ideas/open-source-ideas/issues/76#issuecomment-410540340"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 364748348\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by dannycolin** [comment]
@KOLANICH I totally understand your point. At the same time, there's already a "Relevant Technology" section where people are putting information about which language the project should be written in. The tag ideas is pretty much the same thing but it add the ability to filter.

If we take your point in consideration I think the "Relevant Technology" section should also be reconsidered or redesigned because it can create confusion. For example, if I see a project that specify C++ in the relevant technology section I'll probably skip it immediately since I have not enough experience with that language.

**Comment by FredrikAugust** [comment]
I think that's a pretty good idea. Optional explicitness; tell the creator of the issue that he/she should add a programming language if applicable, and if not leave it be.

By doing that I (or another maintainer) can swing by and slap on the label corresponding to the programming language suggested.

By doing this a C++ can search for any C++ projects, and if nothing shows up, he/she can scroll through the rest of the issues that are not labeled any other programming language, and see if those projects fits his/her wishes.

**Comment by KOLANICH** [comment]
>example, if I see a project that specify C++ in the relevant technology section I'll probably skip it immediately since I have not enough experience with that language.

I won't since that section is just a suggestion and situated after the text describing the idea; when you have reached that section you usually have some understanding if the languagesnyou know are suitable for that.

**Comment by dannycolin** [comment]
@KOLANICH maybe you won't because you know the project ;). But I'm sure a lot of people wil skip it. It should be obvious if a section is a "suggestion" or not. When you present something we don't need to thing "how I will see it" but "how someone else (for whatever reason) will see it".

**Comment by KOLANICH** [comment]
In my opinion your vision of that section is strange and surprising.

**Comment by dannycolin** [comment]
It's ok to disagree and debate the pros and cons of an idea but it isn't to dismiss it with an argument like "your vision of that section is strange and surprising."

Isn't that agaisnt your CoC (Being respectful of differing viewpoints and experiences). Btw it isn't something very welcoming to say to somenone.

**Comment by KOLANICH** [comment]
@dannycolin, I'm sorry, if my comment may have looked impolite. You have told me that that I should think how anyone else would understand that section. I have clarified that in my opinion people would consider that section as a recommendation "this language may be useful" rather than a hard rule "if one is unfamiliar with this language this idea is not for him".

**Comment by mikaelbr** [comment]
Moved to https://github.com/open-source-ideas/meta/issues/3
